name: CI - Build & Test (Dev)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build src/CaseFlowDataPackage/CaseFlowDataPackage.sln -c Release --no-restore

      - name: Run tests
        run: dotnet test src/CaseFlowDataPackage/CaseFlowDataPackage.sln -c Release --no-build --verbosity normal
