name: publish-release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  pack-and-push:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref_name, '-dev.')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }

      - name: Extract version from tag
        id: ver
        run: echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

      - name: Restore
        run: dotnet restore CaseFlowDataPackage/CaseFlowDataPackage.sln

      - name: Build
        run: dotnet build CaseFlowDataPackage/CaseFlowDataPackage.sln -c Release --no-restore

      - name: Pack (stable)
        run: dotnet pack CaseFlowDataPackage/CaseFlowDataPackage/CaseFlowDataPackage.csproj -c Release -o ./artifacts -p:Version=${{ steps.ver.outputs.version }}

      - name: Push to GitHub Packages
        run: |
         dotnet nuget push "./artifacts/*.nupkg" \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --api-key "${{ secrets.GITHUB_TOKEN }}" \
          --skip-duplicate